version: '3.8'
services:
  ops:
    image: kidsdev/ops:${TAG}
    restart: always
    volumes:
      - ./local_settings.py:/code/ultimate/local_settings.py
      - ./static_deploy:/code/static_deploy
      - ./media:/code/media
    ports:
      - 127.0.0.1:${PORT}:80
