# Generated by Django 2.0.2 on 2018-02-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=120)),
                ('sort', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Docker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=120)),
                ('sort', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.AddField(
            model_name='compose',
            name='dockers',
            field=models.ManyToManyField(to='docker.Docker'),
        ),
    ]
