# Generated by Django 2.0.2 on 2018-02-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart', '0001_initial'),
        ('docker', '0001_initial'),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart.Chart')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=120)),
                ('type', models.SmallIntegerField(choices=[(1, 'Stacked Area')])),
                ('sort', models.IntegerField(db_index=True, default=0)),
                ('docker_compose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker.Compose')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='node.Node')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor'),
        ),
    ]
