# Generated by Django 2.0.7 on 2018-07-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-datetime_create'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.TextField()),
                ('result', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-datetime_create'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('field', models.CharField(max_length=255)),
                ('sort', models.SmallIntegerField(db_index=True, default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Template'), (1, 'Task')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField()),
                ('datetime_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-datetime_update'],
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='history',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
