# Generated by Django 2.0.2 on 2018-02-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docker', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=120)),
                ('path', models.CharField(max_length=255)),
                ('sort', models.IntegerField(db_index=True, default=0)),
                ('docker_compose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker.Compose')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Server')),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
