# Generated by Django 2.0.7 on 2018-07-14 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'develop'), (2, 'business')])),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(-1, 'Failed'), (0, 'Waiting'), (1, 'Running'), (2, 'Completed')])),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-datetime_create'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.CharField(default='40', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.SmallIntegerField(choices=[(-3, 'Deleted'), (-2, 'Waiting Delete'), (-1, 'Pause'), (0, 'Waiting'), (1, 'Pending'), (2, 'Live')], default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='tag',
            field=models.CharField(default='master', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.Node'),
        ),
    ]
