# Generated by Django 2.0.7 on 2018-07-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20180714_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='docker_compose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docker.Compose'),
        ),
    ]
