# Generated by Django 2.1 on 2018-08-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=24)),
                ('secret', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('datetime_create', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version.Config')),
            ],
        ),
    ]
