# Generated by Django 2.1.1 on 2018-09-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-datetime_create']},
        ),
    ]
